import type { PlaybookDefinition } from "./playbookTypes.js";

export const cryptoPlaybooks: PlaybookDefinition[] = [
  {
    name: "BTC Trend Continuation",
    assetType: "crypto",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["BTC trend bullish", "Price above key moving averages", "Volume confirms"],
    entryRules: ["Use spot paper only", "No leverage or futures"],
    invalidationRules: ["BTC loses trend support", "Volume fades"],
    stopLossLogic: "Stop below BTC trend support.",
    takeProfitLogic: "2:1 reward/risk minimum.",
    noTradeConditions: ["BTC trend bearish", "Extreme 24h move"],
    riskRules: ["Half-size compared with stocks", "No leverage, margin, or futures"],
    minimumScore: 75,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "High 24h volume",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "ETH / Large Cap Rotation",
    assetType: "crypto",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["ETH or large caps outperform BTC", "Trend confirms", "Risk/reward valid"],
    entryRules: ["Paper spot only", "Avoid late rotation candles"],
    invalidationRules: ["ETH/BTC rotation fades"],
    stopLossLogic: "Stop below rotation support.",
    takeProfitLogic: "2:1 reward/risk minimum.",
    noTradeConditions: ["BTC risk-off", "Volume weak"],
    riskRules: ["Limit correlated large-cap exposure"],
    minimumScore: 75,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "High 24h volume",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Crypto Momentum Breakout",
    assetType: "crypto",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Breakout above resistance", "24h volume surge", "BTC acceptable"],
    entryRules: ["Avoid >25% 24h chase", "Paper spot only"],
    invalidationRules: ["Breakout fails", "BTC reverses hard"],
    stopLossLogic: "Stop below breakout level.",
    takeProfitLogic: "2:1 reward/risk minimum.",
    noTradeConditions: ["Volatility extreme", "Meme pump risk high"],
    riskRules: ["Reduced size; no leverage"],
    minimumScore: 78,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "High 24h volume and volume surge",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "AI/DePIN Narrative Momentum",
    assetType: "crypto",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Narrative active", "Multiple similar assets moving", "Volume confirms"],
    entryRules: ["Avoid illiquid narrative coins", "Paper spot only"],
    invalidationRules: ["Narrative breadth fades", "Support fails"],
    stopLossLogic: "Stop below narrative support.",
    takeProfitLogic: "2:1 reward/risk minimum.",
    noTradeConditions: ["No narrative confirmation", "Low liquidity"],
    riskRules: ["Limit same-narrative exposure"],
    minimumScore: 77,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "High 24h volume",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Oversold Crypto Rebound",
    assetType: "crypto",
    allowedRegimes: ["neutral", "bullish"],
    setupConditions: ["Asset dropped sharply but holds support", "BTC not collapsing", "Volume stabilizes"],
    entryRules: ["Wait for support confirmation", "Smaller paper size"],
    invalidationRules: ["Support breaks", "BTC collapses"],
    stopLossLogic: "Stop below rebound support.",
    takeProfitLogic: "2:1 reward/risk minimum.",
    noTradeConditions: ["BTC risk-off", "No support hold"],
    riskRules: ["Reduced size; no leverage"],
    minimumScore: 72,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "Adequate 24h volume",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Volatility Contraction Breakout",
    assetType: "crypto",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Volatility contracts", "Breakout begins", "Volume expands"],
    entryRules: ["Enter near breakout; avoid late chase", "Paper spot only"],
    invalidationRules: ["Range fails", "Volume does not expand"],
    stopLossLogic: "Stop below contraction range.",
    takeProfitLogic: "2:1 reward/risk minimum.",
    noTradeConditions: ["Volatility already extreme", "BTC bearish"],
    riskRules: ["Reduced size until proven"],
    minimumScore: 76,
    minimumTimeframeAlignment: "aligned",
    minimumLiquidity: "High 24h volume",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  }
];
