import type { PlaybookDefinition } from "./playbookTypes.js";

export const stockPlaybooks: PlaybookDefinition[] = [
  {
    name: "Momentum Breakout",
    assetType: "stock",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Price above EMA 20 and EMA 50", "Relative volume above 2x", "Breakout above recent resistance"],
    entryRules: ["Enter only near breakout or controlled retest", "Avoid extended gaps"],
    invalidationRules: ["Breaks breakout level", "Volume fades below average"],
    stopLossLogic: "Stop below breakout/retest support.",
    takeProfitLogic: "Minimum 2:1 reward/risk, scale only in paper.",
    noTradeConditions: ["Daily move above 25%", "Risk-off market", "No stop-loss"],
    riskRules: ["1% max account risk", "No same-sector concentration"],
    minimumScore: 75,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "1M shares and 1.5x relative volume",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Pullback To Support",
    assetType: "stock",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Uptrend intact", "Pullback near EMA 20/50 or support", "RSI not extremely overbought"],
    entryRules: ["Wait for support hold", "Avoid catching a breakdown candle"],
    invalidationRules: ["Support fails", "Daily trend turns bearish"],
    stopLossLogic: "Stop below support shelf.",
    takeProfitLogic: "Target prior high or 2:1 reward/risk.",
    noTradeConditions: ["Weak market regime", "No volume stabilization"],
    riskRules: ["Reduced size when market is mixed"],
    minimumScore: 70,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "1M shares",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Earnings Continuation",
    assetType: "stock",
    allowedRegimes: ["bullish", "neutral", "high volatility"],
    setupConditions: ["Earnings catalyst confirmed", "Volume above average", "Post-earnings level holds"],
    entryRules: ["Avoid first candle chase", "Enter after hold/retest"],
    invalidationRules: ["Loses post-earnings low", "Guidance news reverses"],
    stopLossLogic: "Stop below post-catalyst support.",
    takeProfitLogic: "2:1 reward/risk or next resistance.",
    noTradeConditions: ["Extreme gap chase", "No confirmed catalyst"],
    riskRules: ["Reduced size during high volatility"],
    minimumScore: 78,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "2M shares",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Sector Strength Rotation",
    assetType: "stock",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Sector outperforming", "Peers confirming move", "Strong relative strength"],
    entryRules: ["Prefer leader with liquidity", "Avoid laggard chase"],
    invalidationRules: ["Sector breadth fades", "Leader loses support"],
    stopLossLogic: "Stop below sector leader support.",
    takeProfitLogic: "2:1 reward/risk or rotation target.",
    noTradeConditions: ["Sector breadth below threshold", "Crowded overextension"],
    riskRules: ["Limit same-sector exposure"],
    minimumScore: 75,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "1M shares and strong market cap",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Oversold Quality Rebound",
    assetType: "stock",
    allowedRegimes: ["neutral", "bullish"],
    setupConditions: ["RSI below threshold", "Acceptable fundamentals", "Price near support"],
    entryRules: ["Wait for reversal confirmation", "Never average down"],
    invalidationRules: ["Support fails", "Bad catalyst appears"],
    stopLossLogic: "Stop below oversold support.",
    takeProfitLogic: "2:1 reward/risk into mean reversion.",
    noTradeConditions: ["Strong bearish regime", "Poor fundamentals"],
    riskRules: ["Smaller paper size"],
    minimumScore: 72,
    minimumTimeframeAlignment: "mixed",
    minimumLiquidity: "1M shares",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  },
  {
    name: "Low-Volatility Trend Continuation",
    assetType: "stock",
    allowedRegimes: ["bullish", "neutral"],
    setupConditions: ["Stable trend", "Volatility contraction", "Price above key averages"],
    entryRules: ["Enter near support or range break", "Avoid low-volume drift"],
    invalidationRules: ["Breaks moving average support"],
    stopLossLogic: "Stop below low-volatility base.",
    takeProfitLogic: "Trail paper target after 2:1 is available.",
    noTradeConditions: ["Volume too low", "Risk-off market"],
    riskRules: ["Normal size only when strategy proven"],
    minimumScore: 74,
    minimumTimeframeAlignment: "aligned",
    minimumLiquidity: "1M shares",
    requiredProofLevel: "PAPER_TESTING",
    enabled: true
  }
];
