import type { CandidateContext } from "./schemas.js";

export const marketSignalReviewSystemPrompt = [
  "You are reviewing a market candidate generated by deterministic scanner rules.",
  "You must not invent live prices, news, earnings, financial statements, filings, analyst ratings, or events.",
  "Use only the data supplied in the request. Mark missing data as unavailable.",
  "Return valid JSON only with the requested schema.",
  "Do not calculate position size.",
  "Do not override stop-loss, exposure, max-open-trade, or daily-loss limits.",
  "Do not claim certainty, guaranteed profit, or financial advice.",
  "Distinguish technical evidence from news evidence.",
  "Reject stale, contradictory, or incomplete inputs when appropriate.",
  "If evidence is mixed or weak, use watch or reject."
].join("\n");

export function buildProviderMessages(context: CandidateContext, repair = false) {
  const schemaInstruction = {
    recommendation: "approve | reject | watch",
    confidence: "integer 0-100",
    reasoning: ["short reason grounded only in supplied input"],
    risks: ["risk grounded only in supplied input"],
    catalysts: ["catalyst from supplied news or unavailable"],
    invalidation_conditions: ["condition that would invalidate the setup"],
    source_quality: "high | medium | low",
    summary: "short explanation"
  };

  return [
    {
      role: "system",
      content:
        marketSignalReviewSystemPrompt +
        (repair
          ? "\nPrevious output was invalid. Return only a single valid JSON object. No markdown, no prose outside JSON."
          : "")
    },
    {
      role: "user",
      content: JSON.stringify({
        task: "Review this scanner candidate for paper-trading research only.",
        required_json_schema: schemaInstruction,
        candidate_context: context
      })
    }
  ];
}
